### ISSUE TITLE
ID problems with Gramps and Ancestry

### ISSUE THREAD

**Issue by ennoborg** [francoisforster/gedcom-cleanup#2]
When I compare files generated by Gramps and Ancestry, I run into two different problems:
1. The program complains about an unrecognized number UBM,
2. The program complains about unrecognized numbers like 332108160602.

The first problem is linked to Gramps using "@SUBM@" as the submitter ID, and the program assuming that the ID (or pointer) is a single character followed by a number.

The second problem is linked to the length of the IDs on Ancestry. They're all the usual character followed by a number, but that number is 12 digits long, so it's not an int.

**Comment by francoisforster** [comment]
@ennoborg can you paste a snippet of the data the program has trouble with?

**Comment by francoisforster** [comment]
Or does it match
```
1 SUBM @SUBM@
0 @SUBM@ SUBM
1 NAME ...
0 @I332108160602@ INDI
```

**Comment by francoisforster** [comment]
If that's the case, it should be fixed with https://github.com/francoisforster/gedcom-cleanup/commit/7318dfd6ff990d6780ba54375d300f0f19a80cee

**Comment by ennoborg** [comment]
You got that right, and the fix works well, but now it turns out that Ancestry doesn't follow the GEDCOM standard for dates, so your string comparison will always fail. That's because Ancestry writes all month names in full, using upper and lower case.

So it looks like you need shortDate vars in Event.Matches, but I don't know whether you want to open a new issue for that.

**Comment by francoisforster** [comment]
@ennoborg do you mind opening a new issue for it and attaching a snippet of the offending dates?

**Comment by francoisforster** [comment]
Closing this issue as the id problem is fixed
