### ISSUE TITLE
Compare fails on dates in Ancestry exports

### ISSUE THREAD

**Issue by ennoborg** [francoisforster/gedcom-cleanup#3]
GEDCOM files exported from Ancestry have non standard dates, meaning that all month names are written in full, so JAN becomes January, and so forth. This means that all date comparisons fail, even for MAY, which is exported as May.

In the attached file, you can also find other non standard constructs, like UID for _UID and _FSID for _FSFTID.
[ancestry.txt](https://github.com/francoisforster/gedcom-cleanup/files/7654204/ancestry.txt)
GEDCOM uploaded as TXT to please GitHub. :-)

**Comment by francoisforster** [comment]
Should be fixed with https://github.com/francoisforster/gedcom-cleanup/commit/5aa1b43d542558c0564795f8e68eb9805ae472ea

**Comment by ennoborg** [comment]
Not here. LocalDate expects a date in the user's local language, which in my case is Dutch. Ancestry uses the long US (English) form.

**Comment by francoisforster** [comment]
Let me know if https://github.com/francoisforster/gedcom-cleanup/commit/6f403184fc7286c71ffc496f0ffded2208483ea2 fixed it

**Comment by ennoborg** [comment]
It did, but Ancestry wouldn't be Ancestry, if they didn't trigger yet another one:

Birth different: Event(date=ABT 1836, place=Zwolle) vs Event(date=about 1836, place=Zwolle)

This gives me the impression that their date export is completely non-standard, and they spell out everything.

**Comment by ennoborg** [comment]
... and that's confirmed by other lines, where Ancestry exported 'before' where BEF is the rule.

**Comment by francoisforster** [comment]
Since this is non-standard gedcom, I'm going to suggest you pre-process the ancestry exported file, or the other file to change ABT with about, BEF with before, etc...
Closing the issue as the month comparison is fixed.
