### ISSUE TITLE
gedcom-compare text output lacks essential information

### ISSUE THREAD

**Issue by ennoborg** [francoisforster/gedcom-cleanup#4]
When I use gedcom-compare to compare files, without creating a new GEDCOM, it produces output like this:

Comparing gedcom files
	Found Marriage on the left but not the right: Event(date=29 NOV 1939, place=Amsterdam)
	Found Marriage on the left but not the right: Event(date=29 NOV 1939, place=Amsterdam)

where an earlier version showed this:

Comparing Henricus Borgsteede (@I00194@}) vs Henricus Borgsteede (@I332108160779@)
	Found Marriage on the left but not the right: Event(date=29 NOV 1939, place=Amsterdam)
Comparing Margaretha Anna Maria Honselaar (@I00305@}) vs Margaretha Anna Maria Honselaar (@I332108160890@)
	Found Marriage on the left but not the right: Event(date=29 NOV 1939, place=Amsterdam)

And the consequence of that is, that with the new version, I have no idea which persons have new information.

**Comment by francoisforster** [comment]
Apologies for that. I just realized that I had compiled the jars with the logging line commented out. I recompiled them just now so this should fix the issue.

**Comment by ennoborg** [comment]
OK, thanks, that's why I didn't see the cause in the source. The new version works fine, and it's easy enough to find persons with changes.
